linux: #группа хостов
  children: #Обозначение, что будет подгруппа хостов
    monitoring:
      hosts:
        elasticsearch:
          ansible_host: fhmgoh3c06qf70cehflv.auto.internal
        kibana:
          ansible_host: fhmkoqbt4a3i3f09cv8o.auto.internal
        zabbix:
          ansible_host: fhml45hq6pmg6ma06nvr.auto.internal
    nginx:
      hosts:
        site-1:
          ansible_host: fhmh65i01b15c8e9kqdj.auto.internal
        site-2:
          ansible_host: epd7hos08oc73p7g8k1t.auto.internal
  vars: #Переменные, доступные и/или используемые для всех подрупп
    ansible_user: "dmitriy_pronin"
    connection_protocol: ssh #тип подключения
    ansible_become: true #Становиться ли другим пользователем после подключения
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    elastic_pass: ""
    el-fqdn: fhmgoh3c06qf70cehflv.auto.internal
    zabix-fqdn: fhml45hq6pmg6ma06nvr.auto.internal
